version: '3.1'
services:
  card-db:
    image: postgres:14-alpine
    container_name: card-db
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: bd
    networks:
      - card-service-network

  card-service:
    build: cardService/
    container_name: card-service
    depends_on:
      - "card-db"
      - "activemq"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://card-db:5432/bd
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - card-service-network
      - general-network

  user-db:
    image: postgres:14-alpine
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: bd
    networks:
      - user-service-network

  user-service:
    build: userService/
    container_name: user-service
    depends_on:
      - "user-db"
      - "activemq"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/bd
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - user-service-network
      - general-network

  store-db:
    image: postgres:14-alpine
    container_name: store-db
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: bd
    networks:
      - store-service-network

  store-service:
    build: storeService/
    container_name: store-service
    depends_on:
      - "store-db"
      - "activemq"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://store-db:5432/bd
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - store-service-network
      - general-network

  auth-service:
    build: authService/
    container_name: auth-service
    networks:
      - auth-service-network
      - general-network

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    #volumes:
    #  - "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - "61616:61616" # broker
      - "8161:8161"   # web
    networks:
      - general-network

  reverse-proxy:
    build: reverse-proxy/
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "card-service"
      - "user-service"
      - "store-service"
      - "auth-service"
      - "static"
    networks:
      - general-network

  static:
    build: web/
    container_name: web
    restart: always
    networks:
      - general-network

networks:
  card-service-network:
  user-service-network:
  store-service-network:
  auth-service-network:
  general-network:
